### ISSUE TITLE
The SPIRV constant translation has issue in translating the signless value 

### ISSUE THREAD

**Issue by chengjunlu** [intel/mlir-extensions#638]
The SPIRV constant translation has issue in translating the signless value. It should use the zero extension instead of sign extension for signless or unsigned value.

This is a Triton requirements memo.

**Comment by Dewei-Wang-sh** [comment]
spirv dialect => spirv
spirv.constant -1 : i16
i16 = ui16
0x0000, ffff, unsigned

0xffff, ffff ,

**Comment by chengjunlu** [comment]
https://github.com/llvm/llvm-project/blob/a1e89710d9fb8d4eb90083d476bd5d77215a960e/mlir/lib/Target/SPIRV/Serialization/Serializer.cpp#L837

The code use the var's value to check the signlessness or signness of the interger instead of the Type.

It should use the Type to decide should use zero extension or sign extension.

**Comment by Stonepia** [comment]
Hi, we have do the experiment, and here is the result:

IR
```MLIR
// -----// IR Dump After CSE (cse) //----- //
module attributes {spirv.target_env = #spirv.target_env<#spirv.vce<v1.4, [Addresses, Float16Buffer, Int64, Int16, Int8, Kernel, Linkage, Vector16, GenericPointer, Groups, Float16, Float64, AtomicFloat32AddEXT, ExpectAssumeKHR], [SPV_EXT_shader_atomic_float_add, SPV_KHR_expect_assume]>, api=OpenCL, #spirv.resource_limits<>>, "triton_gpu.num-warps" = 32 : i32, triton_gpu.shared = 0 : i32, "triton_gpu.threads-per-warp" = 32 : i32} {
  spirv.GlobalVariable @__builtin_var_LocalInvocationId__ built_in("LocalInvocationId") : !spirv.ptr<vector<3xi64>, Input>
  spirv.func @kernel_0d1d(%arg0: !spirv.ptr<i8, CrossWorkgroup> {tt.divisibility = 16 : i32}, %arg1: !spirv.ptr<i8, CrossWorkgroup> {tt.divisibility = 16 : i32}) "None" attributes {spirv.entry_point_abi = #spirv.entry_point_abi<>, sym_visibility = "public"} {
    %__builtin_var_LocalInvocationId___addr = spirv.mlir.addressof @__builtin_var_LocalInvocationId__ : !spirv.ptr<vector<3xi64>, Input>
    %0 = spirv.Load "Input" %__builtin_var_LocalInvocationId___addr : vector<3xi64>
    %1 = spirv.CompositeExtract %0[0 : i32] : vector<3xi64>
    %2 = spirv.SConvert %1 : i64 to i32
    %cst32_i32 = spirv.Constant 32 : i32
    %3 = spirv.UMod %2, %cst32_i32 : i32
    %4 = spirv.UDiv %2, %cst32_i32 : i32
    %cst4_i32 = spirv.Constant 4 : i32
    %5 = spirv.UMod %4, %cst4_i32 : i32
    %cst128_i32 = spirv.Constant 128 : i32
    %6 = spirv.UMod %3, %cst128_i32 : i32
    %cst1_i32 = spirv.Constant 1 : i32
    %7 = spirv.IMul %5, %cst32_i32 : i32
    %8 = spirv.IAdd %6, %7 : i32
    %9 = spirv.IMul %cst1_i32, %8 : i32
    %cst-1_i8 = spirv.Constant -1 : i8
    %10 = spirv.Undef : !spirv.struct<(i8)>
    %11 = spirv.Undef : !spirv.struct<(i32)>
    %12 = spirv.Undef : !spirv.struct<(!spirv.ptr<i8, CrossWorkgroup>)>
    %13 = spirv.PtrAccessChain %arg1[%9] : !spirv.ptr<i8, CrossWorkgroup>, i32
    %true = spirv.Constant true
    %14 = spirv.Undef : i8
    spirv.BranchConditional %true, ^bb1, ^bb2(%14 : i8)
  ^bb1:  // pred: ^bb0
    %15 = spirv.Load "CrossWorkgroup" %13 : i8
    spirv.Branch ^bb2(%15 : i8)
  ^bb2(%16: i8):  // 2 preds: ^bb0, ^bb1
    %17 = spirv.BitwiseXor %16, %cst-1_i8 : i8
    %18 = spirv.PtrAccessChain %arg0[%9] : !spirv.ptr<i8, CrossWorkgroup>, i32
    %19 = spirv.Load "Input" %__builtin_var_LocalInvocationId___addr : vector<3xi64>
    %20 = spirv.CompositeExtract %19[0 : i32] : vector<3xi64>
    %21 = spirv.SConvert %20 : i64 to i32
    %22 = spirv.ULessThan %21, %cst128_i32 : i32
    %23 = spirv.LogicalAnd %true, %22 : i1
    spirv.BranchConditional %23, ^bb3, ^bb4
  ^bb3:  // pred: ^bb2
    spirv.Store "CrossWorkgroup" %18, %17 : i8
    spirv.Branch ^bb4
  ^bb4:  // 2 preds: ^bb2, ^bb3
    spirv.Return
  }
}
```


kernel.spirv
```MLIR
OpCapability Addresses
OpCapability Float16Buffer
OpCapability Int64
OpCapability Int16
OpCapability Int8
OpCapability Kernel
OpCapability Linkage
OpCapability Vector16
OpCapability GenericPointer
OpCapability Groups
OpCapability Float16
OpCapability Float64
OpCapability AtomicFloat32AddEXT
OpCapability ExpectAssumeKHR
OpExtension "SPV_EXT_shader_atomic_float_add"
OpExtension "SPV_KHR_expect_assume"
OpMemoryModel Physical64 OpenCL
OpEntryPoint Kernel %kernel_0d1d "kernel_0d1d" %__builtin_var_LocalInvocationId__
OpExecutionMode %kernel_0d1d SubgroupSize 32
OpName %__builtin_var_LocalInvocationId__ "__builtin_var_LocalInvocationId__"
OpName %kernel_0d1d "kernel_0d1d"
OpDecorate %__builtin_var_LocalInvocationId__ BuiltIn LocalInvocationId
%ulong = OpTypeInt 64 0
%v3ulong = OpTypeVector %ulong 3
%_ptr_Input_v3ulong = OpTypePointer Input %v3ulong
%__builtin_var_LocalInvocationId__ = OpVariable %_ptr_Input_v3ulong Input
%void = OpTypeVoid
%uchar = OpTypeInt 8 0
%_ptr_CrossWorkgroup_uchar = OpTypePointer CrossWorkgroup %uchar
%5 = OpTypeFunction %void %_ptr_CrossWorkgroup_uchar %_ptr_CrossWorkgroup_uchar
%uint = OpTypeInt 32 0
%uint_32 = OpConstant %uint 32
%uint_4 = OpConstant %uint 4
%uint_128 = OpConstant %uint 128
%uint_1 = OpConstant %uint 1
%uchar_4294967295 = OpConstant %uchar 4294967295
%_struct_30 = OpTypeStruct %uchar
%29 = OpUndef %_struct_30
%_struct_32 = OpTypeStruct %uint
%31 = OpUndef %_struct_32
%_struct_34 = OpTypeStruct %_ptr_CrossWorkgroup_uchar
%33 = OpUndef %_struct_34
%bool = OpTypeBool
%true = OpConstantTrue %bool
%38 = OpUndef %uchar
%kernel_0d1d = OpFunction %void None %5
%10 = OpFunctionParameter %_ptr_CrossWorkgroup_uchar
%11 = OpFunctionParameter %_ptr_CrossWorkgroup_uchar
%12 = OpLabel
%13 = OpLoad %v3ulong %__builtin_var_LocalInvocationId__
%14 = OpCompositeExtract %ulong %13 0
%16 = OpSConvert %uint %14
%18 = OpUMod %uint %16 %uint_32
%19 = OpUDiv %uint %16 %uint_32
%21 = OpUMod %uint %19 %uint_4
%23 = OpUMod %uint %18 %uint_128
%25 = OpIMul %uint %21 %uint_32
%26 = OpIAdd %uint %23 %25
%27 = OpIMul %uint %uint_1 %26
%35 = OpPtrAccessChain %_ptr_CrossWorkgroup_uchar %11 %27
OpBranchConditional %true %39 %40
%39 = OpLabel
%41 = OpLoad %uchar %35
OpBranch %40
%40 = OpLabel
%42 = OpPhi %uchar %41 %39 %38 %12
%43 = OpBitwiseXor %uchar %42 %uchar_4294967295
%44 = OpPtrAccessChain %_ptr_CrossWorkgroup_uchar %10 %27
%45 = OpLoad %v3ulong %__builtin_var_LocalInvocationId__
%46 = OpCompositeExtract %ulong %45 0
%47 = OpSConvert %uint %46
%48 = OpULessThan %bool %47 %uint_128
%49 = OpLogicalAnd %bool %true %48
OpBranchConditional %49 %50 %51
%50 = OpLabel
OpStore %44 %43
OpBranch %51
%51 = OpLabel
OpReturn
OpFunctionEnd
```
There will be a `%cst-1_i8 = spirv.Constant -1 : i8`.

When we try the following:

```
$./spirv-as  kernel.spirv
error: 36: 39: Integer 4294967295 does not fit in a 8-bit unsigned integer
```

**Comment by Jianhui-Li** [comment]
@mshahneo  It seems that SPIRV does support sigeless data, by associating the signed or unsigned semantics with SPIRV OP. Like UMOD vs. SMOD, and UDIV vs. SDIV.  It also support operations which yields the same result for both signed and semantics, those are prefixed with "I", like IADD, IMUL. 
 
Chengjun said that one difference between SPIRV and LLVM is that SPIRV doesn't differentiate the signless data type with unsigned data type. So all the signless data would be mapped to unsigned data type.  
         https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpTypeInt

This may create a weird combination that a signed op processing an unsigned data, which is really signed op processing a signless data, and the signless data (appeared as unsigned data) is used as singed data (op semantics overrides the data type).  I find one such case in the above example:
          %47 = OpSConvert %uint %46 
But the compuation is fine, just the dump out could be improved like below, if you prefer accuracy to readabilty. 
          %47 = OpSConvert %uint_or_signless %46
   
But the problem of this example is that SPIRV dialect sign extended the signless constant. What is the rational behind it? @mshahneo  
    %cst-1_i8 = spirv.Constant -1 : i8    //0xff
 =>
   %43 = OpBitwiseXor %uchar %42 %uchar_4294967295  //0xffffffff

**Comment by mshahneo** [comment]
Hi Jianhui (@Jianhui-Li ),

I think the rational came from this part of the specification:
https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_instructions

In the literal section the spec says, 'If a numeric type’s bit width is less than 32-bits, the value appears in the low-order bits of the word, and the high-order bits must be 0 for a floating-point type or integer type with Signedness of 0, or sign extended for an integer type with a Signedness of 1 (similarly for the remaining bits of widths larger than 32 bits but not a multiple of 32 bits).'

Now the question is, does signless mean 'Signedness of 0'?

The specification says (https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_unsigned_versus_signed_integers), signless integers 'select a signedness of 0 to conceptually mean "no sign" (rather than "unsigned").' So my understanding is that the singless integers should be '0-extended' rather than 'sign extended'.


Further evidence that it should be '0-extended' is that, in the example (https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_example) the specification says,

%13 = OpTypeInt 32 0                         ; 32-bit int, sign-less

Signedness value '0' means signless. SPIR-V dialect also uses the same signedness value when converting signless int types (eg., i8, i16, i32)

%uchar = OpTypeInt 8 0              ; found it from a spirv dialect serialized IR
%uint = OpTypeInt 32 0

So based on all these information, my understanding is that, the implementation in SPIR-V dialect is not follwoing the spec and should be updated.

We already know the fix, so I'll open a PR. Before that, I'll just do some simple testing and run it using IMEX (this would mean the SPIRV IR gets compiled by the IGC) to confirm that what I am understanding is right.


P.S., even though we had the soulution, I was not sure if we were right. But after looking into the specification in more detail, and looking into the spirv-tools code, I am convinced now.
@Stonepia , thank you so much for the test case, it really helped me narrow down the issue.

**Comment by mshahneo** [comment]
PR merged. Closing the issue.
https://reviews.llvm.org/D151767
